### ISSUE TITLE
Theme appears to be corrupt

### ISSUE THREAD

**Issue by lo-yak** [dracula/thunderbird#4]
I tried to download the .zip many times, but when I add the add-on to Thunderbird I get this message that it appears to be corrupt and I can't add it.

**Comment by maxfrei750** [comment]
Thanks for the bug report. I was able to reproduce the error, when trying to use the zip (as described in the _Install manually_ section). Installing from [Thunderbird themes ](https://addons.thunderbird.net/en-US/thunderbird/addon/dracula-theme-for-thunderbird/) still works fine. So I suggest that you try to install the theme that way instead.

@zenorocha I removed the manual installation from INSTALL.md for now. Can you please ensure that https://draculatheme.com/thunderbird is updated accordingly? Thanks.
